wandb_version: 1

batch_size:
  desc: null
  value: 32
architecture:
  desc: null
  value: DDQN
dataset:
  desc: null
  value: mario_gymnasium
episodes:
  desc: null
  value: 40000
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690906961.801102
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.15.4
      8:
      - 3
      - 5
